
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/money?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  mvc:
    data-format:yyyy-MM-dd

  server:
    session:
      timeout: 3600

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  resources:
    static-locations=classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/,classpath:/upload/



